version: '3.6'

networks:
  gateway:
    driver: bridge

services:
  organizr:
    image: lsiocommunity/organizr
    restart: always
    networks:
      - default
      - gateway
    ports:
      - 81:80
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
    labels:
      - "traefik.enable=true"
      - "traefik.backend=organizr"
      - "traefik.frontend.rule=Host:organizr.${DOMAINNAME}"
#      - "traefik.frontend.rule=Host:${DOMAINNAME}; PathPrefixStrip:/organizr"
      - "traefik.port=80"
      - "traefik.docker.network=notflix_gateway"
    volumes:
      - ${ORGANIZR_CONFIG}:/config
  plex:
    image: plexinc/pms-docker
    restart: always
    hostname: ${HOSTNAME}
    networks:
      - default
      - gateway
    ports:
      - 32400:32400/tcp
      - 3005:3005/tcp
      - 8324:8324/tcp
      - 32469:32469/tcp
      - 1900:1900/udp
      - 32410:32410/udp
      - 32412:32412/udp
      - 32413:32413/udp
      - 32414:32414/udp
    environment:
      - TZ=${TZ}
      - PLEX_UID=${PUID}
      - PLEX_GID=${PGID}
      - PLEX_CLAIM=${PLEX_CLAIM}
      - ADVERTISE_IP=${ADVERTISE_IP}
      - CHANGE_CONFIG_DIR_OWNERSHIP=${CHANGE_CONFIG_DIR_OWNERSHIP}
    volumes:
      - ${PLEX_CONFIG}:/config
      - ${TRANSCODE_TMP_DIR}:/transcode
      - ${MEDIA_DIR}:/data
  tautulli:
    image: linuxserver/tautulli
    restart: always
    links:
      - plex
    networks:
      - default
      - gateway
    ports:
      - 8181:8181/tcp
      - 8181:8181/udp
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.auth.basic=${BAUTH_USER}:${BAUTH_PASSWORD}"
      - "traefik.backend=tautulli"
      - "traefik.frontend.rule=Host:tautulli.${DOMAINNAME}"
#      - "traefik.frontend.rule=Host:${DOMAINNAME}; PathPrefixStrip: /tautulli"
      - "traefik.port=8181"
      - "traefik.docker.network=notflix_gateway"
    volumes:
      - ${TAUTULLI_CONFIG}:/config
      - ${PLEX_CONFIG}/Library/Application Support/Plex Media Server/Logs:/logs:ro
  ombi:
    image: linuxserver/ombi
    restart: always
    networks:
      - default
      - gateway
    ports:
      - 3579:3579/tcp
      - 3579:3579/udp
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
    labels:
      - "traefik.enable=true"
      - "traefik.backend=ombi"
      - "traefik.frontend.rule=Host:ombi.${DOMAINNAME}"
#      - "traefik.frontend.rule=Host:${DOMAINNAME}; PathPrefixStrip: /ombi"
      - "traefik.port=3579"
      - "traefik.docker.network=notflix_gateway"
    volumes:
      - ${OMBI_CONFIG}:/config
